[directory]
style = "bold blue"

[character]
symbol = "$"
error_symbol = "✗"
use_symbol_for_status = true

[package]
disabled = true

[git_branch]
style = "fg:underline bold dimmed white"

[git_status]
style = "bold cyan"
show_sync_count = true

